---
# roles/packages/vars/main.yml

# Packages from official Arch repositories
arch_packages:
  - alacritty
  - atuin
  - base
  - base-devel
  - brave-bin
  - btrfs-progs
  - cmark
  - cpio
  - dosfstools
  - efibootmgr
  - efivar
  - entr
  - espanso-x11
  - evtest
  - exo
  - firefox
  - flameshot
  - fnm-bin
  - garcon
  - gemini-cli-git
  - git
  - grml-zsh-config
  - grub
  - gvim
  - htop
  - imagemagick
  - iptables-nft
  - kitty
  - lightdm
  - lightdm-gtk-greeter
  - linux-aarch64
  - mousepad
  - nano
  - neovim
  - pandoc-bin
  - parole
  - polkit
  - potrace
  - qemu-guest-agent
  - ristretto
  - rsync
  - rustup
  - spice-vdagent
  - sudo
  - terminus-font
  - thunar
  - thunar-archive-plugin
  - thunar-media-tags-plugin
  - thunar-volman
  - tmux
  - tor
  - ttf-nerd-fonts-symbols
  - ttf-nerd-fonts-symbols-common
  - tumbler
  - usbutils
  - w3m
  - wezterm
  - wxwidgets-gtk3
  - xclip
  - xfburn
  - xfce4-appfinder
  - xfce4-artwork
  - xfce4-battery-plugin
  - xfce4-clipman-plugin
  - xfce4-cpufreq-plugin
  - xfce4-cpugraph-plugin
  - xfce4-dict
  - xfce4-diskperf-plugin
  - xfce4-eyes-plugin
  - xfce4-fsguard-plugin
  - xfce4-genmon-plugin
  - xfce4-mailwatch-plugin
  - xfce4-mount-plugin
  - xfce4-mpc-plugin
  - xfce4-netload-plugin
  - xfce4-notes-plugin
  - xfce4-notifyd
  - xfce4-panel
  - xfce4-places-plugin
  - xfce4-power-manager
  - xfce4-pulseaudio-plugin
  - xfce4-screensaver
  - xfce4-screenshooter
  - xfce4-sensors-plugin
  - xfce4-session
  - xfce4-settings
  - xfce4-smartbookmark-plugin
  - xfce4-systemload-plugin
  - xfce4-taskmanager
  - xfce4-terminal
  - xfce4-time-out-plugin
  - xfce4-timer-plugin
  - xfce4-verve-plugin
  - xfce4-wavelan-plugin
  - xfce4-weather-plugin
  - xfce4-whiskermenu-plugin
  - xfce4-xkb-plugin
  - xfconf
  - xfdesktop
  - xfwm4
  - xfwm4-themes
  - xorg-xev
  - xorg-xinput
  - yay
  - zenity

# Packages from AUR
aur_packages:
  - brave-bin
  - espanso-x11
  - fnm-bin
  - gemini-cli-git
  - pandoc-bin
  - yay